### ISSUE TITLE
SpongeForge start with GUI

### ISSUE THREAD

**Issue by randombyte-developer** [Qixalite/SpongeStart#11]
In version 1.4.5 the Forge server starts with a GUI but it should start without one.

**Comment by thomas15v** [comment]
So far I know spongeforge removes the GUI. Did they changed that? Anyway you could always add ```-nogui``` to the startup parameters.

**Comment by thomas15v** [comment]
Looks like the issue is that forge maven repo has changed it's file format.
It's the same issue like #10 #9.
