### ISSUE TITLE
Quick questions, & possibly features.

### ISSUE THREAD

**Issue by ryantheleach** [Qixalite/SpongeStart#12]
Using this is it possible to not only run, but also debug plugins?

If debugging a server, is the watchdog / client timeouts disabled? It's really annoying when debugging and you have paused the debugger and the client drops before you get to see the end.

If you have any way of resolving this, even with co-operation with the Sponge Staff it could make this a really helpful tool for beginners.

**Comment by thomas15v** [comment]
Yes
If you debug for to long your client will disconnect and the server (forge) will stop.
Hmmm as far as I am aware sponge staff wants to have an idea plugin. But I haven't approached them or they me yet.
