### ISSUE TITLE
Never generates the task

### ISSUE THREAD

**Issue by pie-flavor** [Qixalite/SpongeStart#14]
Not once has SpongeStart ever generated an IntelliJ task for SpongeVanilla.

**Comment by thomas15v** [comment]
Can you show me your build.gradle? It's kinda hard to figure out what is wrong without some information.

But honestly I think something might be wrong on this part: https://github.com/Qixalite/SpongeStart/blob/master/src/main/java/com/qixalite/spongestart/tasks/GenerateIntelijTask.java#L60-L64. I also sometimes get errors, but after `gradle --stop` they usally go away.

**Comment by pie-flavor** [comment]
[build.gradle](http://pastebin.com/C1fss1ht)
don't know where the build log is located

**Comment by thomas15v** [comment]
The latest version of spongegradle is 1.5.1. So far I know 0.6 was a fail release.
