### ISSUE TITLE
No way to get bleeding builds

### ISSUE THREAD

**Issue by pie-flavor** [Qixalite/SpongeStart#15]
As of the current versions of both Sponge and SpongeStart, setting the build to 'LATEST' will only accept beta (read: release) (i.e. 4.x) builds. Bleeding builds (i.e. 5.x) do not show up under this, and additionally there isn't a way to make it show them (since you just use Integer.valueOf(String) to parse it).

**Comment by pie-flavor** [comment]
@thomas15v any status?

**Comment by thomas15v** [comment]
Yeah to many projects atm xD. I can't figure out witch one to take first :/. Ill come back to this eventually I hope.

**Comment by randombyte-developer** [comment]
A temporary solution is to use the Forge server. With only
`spongestart {
    eula true
}`
as configuration it will download for the latest bleeding release for Forge.

**Comment by thomas15v** [comment]
```groovy
spongestart{
   eula true

   //optional configs
   spongeVanillaBuild '1.10.2-5.0.0-BETA-100'
}
```
This should normally get you bleeding builds now.
