### ISSUE TITLE
Upload SpongeStart to gradle plugin portal

### ISSUE THREAD

**Issue by kinggoesgaming** [Qixalite/SpongeStart#6]
Currently the only option we have is using your jitpack repo and a buildscript... However using the new plugins{}  systems is not supported. It is suggested that you upload the plugin on BinTray. The result would be something like this

```groovy
buildscript {
    repositories{
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.github.liach:SpongeStart:9d975fb'
    }
}
```

to 

```groovy
plugins {
    id 'com.github.liach:SpongeStart' version 'version'
}
```

Note I am using @liach's patch version obviously your plugin is gonna have your group id

**Comment by Minecrell** [comment]
Bintray and the Gradle plugin portal are different things, you need to upload the plugin to the [Gradle plugin portal](https://plugins.gradle.org/docs/submit), not Bintray. Bintray is the old way, however it's much more complicated than the plugin portal directly now.

**Comment by kinggoesgaming** [comment]
woops i meant gradle plugin portal :P

**Comment by thomas15v** [comment]
Hmmm, but this is a minecraft only plugin. Not sure how helpful it would be on the gradle portal.

**Comment by thomas15v** [comment]
Should be functional now:
```groovy
plugins {
  id "com.qixalite.spongestart" version "1.4.2"
}
```
Still need to test it tho :smile_cat:.

**Comment by liach** [comment]
Thanks @thomas15v! [It works.](https://github.com/FlibioStudio/Updatifier/commit/76fbfd7cac425a51902f79df6ab63d8f425f849a)

**Comment by kinggoesgaming** [comment]
can confirm works as expected..
